n = input ('Digite Algo:')
print('Segue abaixo as informações:')
print (n)
print('Tipo primitivo:', type(n))
print('só tem espaços?:', n.isspace())
print('É numerico:', n.isnumeric())
print('É alpha númerico:', n.isalnum())
print('É alfabético:', n.isalpha())
print('Está em maiúsculas?', n.isupper())
print('Está em minúsculas?', n.islower())
print('Está capitalizada?', n.istitle())