nome = input('Coloque aqui seu nome completo: ')
nomeG = nome.upper()
nomeP = nome.lower()
nomeT = len(nome.replace(' ',''))
nome2 = len(nome.split()[0])
print('A-Aqui está seu nome em maiusculo: {}'.format(nomeG))
print('B-Aqui está seu nome em minusculo: {}'.format(nomeP))
print('C-seu nome tem: {} letras sem considerar espaços.'.format(nomeT))
print('D-Seu primeiro nome tem: {} letras.'.format(nome2))
